---
abstract: 'Read and write CODEOWNERS files'
author:
  - 'Charles McGarvey <chazmcgarvey@brokenzipper.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  FindBin: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.014, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-Codeowners
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  File::Codeowners:
    file: lib/File/Codeowners.pm
    version: '0.52'
  File::Codeowners::Util:
    file: lib/File/Codeowners/Util.pm
    version: '0.52'
  File::Codeowners::Util::Process:
    file: lib/File/Codeowners/Util.pm
    version: '0.52'
  Test::File::Codeowners:
    file: lib/Test/File/Codeowners.pm
    version: '0.52'
requires:
  Carp: '0'
  Encode: '0'
  Exporter: '0'
  IPC::Open2: '0'
  Path::Tiny: '0.089'
  Scalar::Util: '0'
  Text::Gitignore: '0'
  perl: v5.10.1
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/chazmcgarvey/File-Codeowners/issues
  homepage: https://github.com/chazmcgarvey/File-Codeowners
  repository: https://github.com/chazmcgarvey/File-Codeowners.git
version: '0.52'
x_authority: cpan:CCM
x_generated_by_perl: v5.28.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
